capacity = "2"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
deeplink_base_url = "https://www-ccd.aat.platform.hmcts.net/case/"
service_bus_queue_name = "ctsc-work-allocation-queue-aat"
smtp_enabled = "true"
test_enpooints_enabled = "true"
ccd_dry_run = "false"
minus_time_from_current = "7"
