idam_api_url            = "https://idam-api.demo.platform.hmcts.net"
deeplink_base_url       = "https://www-ccd.demo.platform.hmcts.net/case/"
service_bus_queue_name  = "ctsc-work-allocation-queue-demo"
smtp_enabled            = "true"
test_enpooints_enabled  = "true"
minus_time_from_current = "7"
liquibase_enabled       = "false"
